export const REQUIRED_PYTHON_VERSION = '3.10.0';

export const SCREEN_WIDTH = 1920;
export const SCREEN_HEIGHT = 1080;
export const SCREEN_HEIGHT_OFFSET = 180;

export const TOBII_SAMPLE_RATE = 60;

export const HEAD_TEXT_HEIGHT_OFFSET = 20;
export const BLOCK_BOTTOM_OFFSET = 30;

export const STATIONARY_DECISION_THRESHOLD_PIXEL = 200;
export const STATIONARY_DECISION_THRESHOLD_MILLISECOND = 300;

export const GAZE_FILL_RATIO_THRESHOLD = 0.5;
export const GAZE_FILL_RATIO_THRESHOLD_LOWER_LIMIT = 0.2;
